import type { FormEvent, ReactNode } from "react";
import { useQuery } from "@tanstack/react-query";
import { Alert, AlertDescription, AlertIcon, Badge, Box, Button, Card, CardBody, Flex, FormControl, FormLabel, Heading, Select, Spinner, Stat, StatLabel, StatNumber, Table, Tbody, Td, Text, Th, Thead, Tr } from "@chakra-ui/react";
import { api } from "../../client/api";
import { errorText } from "../../lib/format";

export const active = <T extends { is_active: boolean }>(items: T[] | undefined) => items?.filter((item) => item.is_active) ?? [];
export const confirmDelete = (name: string) => window.confirm(`¿Inactivar ${name}? Esta acción conserva el historial.`);
export function PageTitle({ title, description }: { title: string; description: string }) { return <Box><Heading size="lg">{title}</Heading><Text color="gray.500" mt="1">{description}</Text></Box>; }
export function Field({ label, children, required = false }: { label: string; children: ReactNode; required?: boolean }) { return <FormControl isRequired={required}><FormLabel fontSize="sm">{label}</FormLabel>{children}</FormControl>; }
export function Metric({ label, value, color }: { label: string; value: string; color?: string }) { return <Stat><StatLabel fontSize="xs">{label}</StatLabel><StatNumber fontSize="lg" color={color}>{value}</StatNumber></Stat>; }
export function Status({ active: isActive }: { active: boolean }) { return <Badge ml="2" colorScheme={isActive ? "green" : "gray"}>{isActive ? "Activo" : "Inactivo"}</Badge>; }
export function Loading() { return <Flex py="16" justify="center"><Spinner color="brand.500" size="lg" /></Flex>; }
export function ErrorBox({ error }: { error: unknown }) { return <Alert status="error"><AlertIcon /><AlertDescription>{errorText(error)}</AlertDescription></Alert>; }
export function Empty({ text }: { text: string }) { return <Box py="10" bg="white" borderRadius="md" textAlign="center"><Text color="gray.500">{text}</Text></Box>; }
export function Cancel({ editing, onClick }: { editing: boolean; onClick: () => void }) { return editing ? <Button mt="5" ml="3" onClick={onClick}>Cancelar</Button> : null; }
export function Editor({ title, children, onSubmit, loading, error }: { title: string; children: ReactNode; onSubmit: () => void; loading: boolean; error: Error | null }) { return <Card><CardBody><Heading size="sm" mb="4">{title}</Heading><form onSubmit={(event: FormEvent) => { event.preventDefault(); onSubmit(); }}>{children}<Button mt="5" type="submit" colorScheme="brand" isLoading={loading}>Guardar</Button>{error && <Box mt="3"><ErrorBox error={error} /></Box>}</form></CardBody></Card>; }
export function DataTable({ headers, children, empty }: { headers: string[]; children: ReactNode; empty: string }) { const isEmpty = Array.isArray(children) && children.length === 0; return <Card><CardBody p="0"><Box className="table-wrap"><Table size="sm"><Thead><Tr>{headers.map((header) => <Th key={header}>{header}</Th>)}</Tr></Thead><Tbody>{children}</Tbody></Table></Box>{isEmpty && <Empty text={empty} />}</CardBody></Card>; }
export function CatalogueSelect<T extends { id: string; nombre: string }>({ label, value, onChange, items, disabled = false }: { label: string; value: string; onChange: (value: string) => void; items: T[]; disabled?: boolean }) { return <Field label={label}><Select value={value} onChange={(event) => onChange(event.target.value)} placeholder={`Selecciona ${label.toLowerCase()}`} isDisabled={disabled}><option value="">Sin asignar</option>{items.map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</Select></Field>; }
export function AccountSelect({ value, onChange }: { value: string; onChange: (value: string) => void }) { const accounts = useQuery({ queryKey: ["cuentas", "active"], queryFn: () => api.cuentas() }); if (accounts.isLoading) return <Spinner size="sm" />; if (accounts.isError) return <ErrorBox error={accounts.error} />; return <Select value={value} onChange={(event) => onChange(event.target.value)} placeholder="Selecciona una cuenta" required>{active(accounts.data).map((account) => <option key={account.id} value={account.id}>{account.alias} ({account.moneda})</option>)}</Select>; }
