import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button, Card, CardBody, HStack, Input, Select, SimpleGrid, Stack, Td, Text, Tr } from "@chakra-ui/react";
import { api, type CentroResultado, type RubroResultado } from "../client/api";
import { confirmDelete, DataTable, Editor, ErrorBox, Field, PageTitle, Status } from "../components/common";
import { download } from "../lib/download";

type Naturaleza = NonNullable<RubroResultado["naturaleza"]>;
const refreshKeys = ["egyp-centros", "egyp-rubros"];
const emptyCenter = { codigo: "", nombre: "", orden: "0" };
const emptyRubro: { codigo: string; nombre: string; naturaleza: Naturaleza; padre_id: string; orden: string } = { codigo: "", nombre: "", naturaleza: "INGRESO", padre_id: "", orden: "0" };

export function ProfitLossAdminPage() {
  const queryClient = useQueryClient();
  const centers = useQuery({ queryKey: ["egyp-centros"], queryFn: () => api.egypCentros(true) });
  const rubros = useQuery({ queryKey: ["egyp-rubros"], queryFn: () => api.egypRubros(true) });
  const [center, setCenter] = useState(emptyCenter);
  const [rubro, setRubro] = useState(emptyRubro);
  const [editingCenter, setEditingCenter] = useState<CentroResultado>();
  const [editingRubro, setEditingRubro] = useState<RubroResultado>();
  const [file, setFile] = useState<File>();
  const refresh = () => refreshKeys.forEach((key) => void queryClient.invalidateQueries({ queryKey: [key] }));
  const saveCenter = useMutation({ mutationFn: () => editingCenter ? api.updateEgypCentro(editingCenter.id, { ...center, orden: Number(center.orden) }) : api.createEgypCentro({ ...center, orden: Number(center.orden) }), onSuccess: () => { refresh(); setCenter(emptyCenter); setEditingCenter(undefined); } });
  const saveRubro = useMutation({ mutationFn: () => { const body = { ...rubro, padre_id: rubro.padre_id || null, orden: Number(rubro.orden) }; return editingRubro ? api.updateEgypRubro(editingRubro.id, body) : api.createEgypRubro(body); }, onSuccess: () => { refresh(); setRubro(emptyRubro); setEditingRubro(undefined); } });
  const upload = useMutation({ mutationFn: () => file ? api.importEgyp(file) : Promise.reject(new Error("Selecciona un archivo Excel.")), onSuccess: () => void queryClient.invalidateQueries({ queryKey: ["egyp-summary"] }) });
  return <Stack spacing="6">
    <PageTitle title="Configuración EGyP" description="Primero define las líneas y rubros; luego usa una sola plantilla para registrar e importar asientos." />
    <Card borderTop="3px solid" borderColor="brand.500"><CardBody><Stack spacing="4"><Text fontWeight="semibold">Importar asientos</Text><Text fontSize="sm" color="gray.500">Descarga la plantilla para consultar líneas, rubros y la guía de tipificación. El rubro es obligatorio; la línea solo puede omitirse cuando exista una regla de distribución.</Text><HStack flexWrap="wrap"><Input type="file" accept=".xlsx" p="1" maxW="360px" onChange={(event) => setFile(event.target.files?.[0])} /><Button variant="outline" onClick={() => void api.download("/api/v1/ganancias-perdidas/plantilla.xlsx").then((blob) => download(blob, "plantilla_egyp.xlsx"))}>Descargar plantilla guiada</Button><Button colorScheme="brand" isDisabled={!file} isLoading={upload.isPending} onClick={() => upload.mutate()}>Importar asientos</Button></HStack>{upload.isError && <ErrorBox error={upload.error} />}{upload.data && <Text color="green.600">Se importaron {upload.data.filas_nuevas} asientos en el lote {upload.data.lote_id}.</Text>}</Stack></CardBody></Card>
    <Editor title={editingCenter ? "Editar línea de negocio" : "Nueva línea de negocio"} onSubmit={() => saveCenter.mutate()} loading={saveCenter.isPending} error={saveCenter.error}><SimpleGrid columns={{ base: 1, md: 3 }} spacing="3"><Field label="Código" required><Input value={center.codigo} onChange={(event) => setCenter({ ...center, codigo: event.target.value })} /></Field><Field label="Nombre" required><Input value={center.nombre} onChange={(event) => setCenter({ ...center, nombre: event.target.value })} /></Field><Field label="Orden"><Input type="number" value={center.orden} onChange={(event) => setCenter({ ...center, orden: event.target.value })} /></Field></SimpleGrid></Editor>
    {centers.data && <DataTable headers={["Código", "Línea de negocio", "Estado", ""]} empty="No hay líneas de negocio.">{centers.data.map((item) => <Tr key={item.id}><Td>{item.codigo}</Td><Td>{item.nombre}</Td><Td><Status active={item.is_active} /></Td><Td><HStack><Button size="sm" onClick={() => { setEditingCenter(item); setCenter({ codigo: item.codigo, nombre: item.nombre, orden: String(item.orden) }); }}>Editar</Button>{item.is_active && <Button size="sm" variant="ghost" colorScheme="red" onClick={() => confirmDelete(item.nombre) && api.deleteEgypCentro(item.id).then(refresh)}>Inactivar</Button>}</HStack></Td></Tr>)}</DataTable>}
    <Editor title={editingRubro ? "Editar rubro" : "Nuevo rubro"} onSubmit={() => saveRubro.mutate()} loading={saveRubro.isPending} error={saveRubro.error}><SimpleGrid columns={{ base: 1, md: 5 }} spacing="3"><Field label="Código" required><Input value={rubro.codigo} onChange={(event) => setRubro({ ...rubro, codigo: event.target.value })} /></Field><Field label="Nombre" required><Input value={rubro.nombre} onChange={(event) => setRubro({ ...rubro, nombre: event.target.value })} /></Field><Field label="Naturaleza" required><Select value={rubro.naturaleza} onChange={(event) => setRubro({ ...rubro, naturaleza: event.target.value as Naturaleza })}>{["INGRESO", "CONTRA_INGRESO", "COSTO_VENTA", "GASTO_OPERATIVO", "INGRESO_FINANCIERO", "GASTO_FINANCIERO", "IMPUESTO"].map((value) => <option key={value}>{value}</option>)}</Select></Field><Field label="Rubro padre"><Select value={rubro.padre_id} onChange={(event) => setRubro({ ...rubro, padre_id: event.target.value })}><option value="">Sin padre: rubro principal</option>{rubros.data?.filter((item) => item.is_active && item.id !== editingRubro?.id).map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</Select></Field><Field label="Orden"><Input type="number" value={rubro.orden} onChange={(event) => setRubro({ ...rubro, orden: event.target.value })} /></Field></SimpleGrid></Editor>
    {rubros.data && <DataTable headers={["Código", "Rubro", "Naturaleza", "Estado", ""]} empty="No hay rubros.">{rubros.data.map((item) => <Tr key={item.id}><Td>{item.codigo}</Td><Td>{item.nombre}</Td><Td>{item.naturaleza}</Td><Td><Status active={item.is_active} /></Td><Td><HStack><Button size="sm" onClick={() => { setEditingRubro(item); setRubro({ codigo: item.codigo, nombre: item.nombre, naturaleza: item.naturaleza, padre_id: item.padre_id ?? "", orden: String(item.orden) }); }}>Editar</Button>{item.is_active && <Button size="sm" variant="ghost" colorScheme="red" onClick={() => confirmDelete(item.nombre) && api.deleteEgypRubro(item.id).then(refresh)}>Inactivar</Button>}</HStack></Td></Tr>)}</DataTable>}
  </Stack>;
}
