import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button, Card, CardBody, HStack, Input, Select, SimpleGrid, Stack, Td, Text, Tr } from "@chakra-ui/react";
import { api, type CentroResultado, type MapeoResultado, type RubroResultado } from "../client/api";
import { confirmDelete, DataTable, Editor, ErrorBox, Field, PageTitle, Status } from "../components/common";
import { download } from "../lib/download";

type Naturaleza = NonNullable<RubroResultado["naturaleza"]>;
const refreshKeys = ["egyp-centros", "egyp-rubros", "egyp-mapeos"];
const emptyCenter = { codigo: "", nombre: "", orden: "0" };
const emptyRubro: { codigo: string; nombre: string; naturaleza: Naturaleza; padre_id: string; orden: string } = { codigo: "", nombre: "", naturaleza: "INGRESO", padre_id: "", orden: "0" };
const emptyMap = { cuenta_contable: "", rubro_id: "", centro_resultado_id: "", vigente_desde: "", vigente_hasta: "" };

export function ProfitLossAdminPage() {
  const queryClient = useQueryClient();
  const refresh = () => refreshKeys.forEach((key) => void queryClient.invalidateQueries({ queryKey: [key] }));
  const centers = useQuery({ queryKey: ["egyp-centros"], queryFn: () => api.egypCentros(true) });
  const rubros = useQuery({ queryKey: ["egyp-rubros"], queryFn: () => api.egypRubros(true) });
  const mappings = useQuery({ queryKey: ["egyp-mapeos"], queryFn: () => api.egypMapeos(true) });
  const [center, setCenter] = useState(emptyCenter);
  const [rubro, setRubro] = useState(emptyRubro);
  const [mapping, setMapping] = useState(emptyMap);
  const [editingCenter, setEditingCenter] = useState<CentroResultado>();
  const [editingRubro, setEditingRubro] = useState<RubroResultado>();
  const [editingMap, setEditingMap] = useState<MapeoResultado>();
  const [file, setFile] = useState<File>();
  const saveCenter = useMutation({ mutationFn: () => editingCenter ? api.updateEgypCentro(editingCenter.id, { ...center, orden: Number(center.orden) }) : api.createEgypCentro({ ...center, orden: Number(center.orden) }), onSuccess: () => { refresh(); setCenter(emptyCenter); setEditingCenter(undefined); } });
  const saveRubro = useMutation({ mutationFn: () => { const body = { ...rubro, padre_id: rubro.padre_id || null, orden: Number(rubro.orden) }; return editingRubro ? api.updateEgypRubro(editingRubro.id, body) : api.createEgypRubro(body); }, onSuccess: () => { refresh(); setRubro(emptyRubro); setEditingRubro(undefined); } });
  const saveMap = useMutation({ mutationFn: () => { const body = { ...mapping, centro_resultado_id: mapping.centro_resultado_id || null, vigente_desde: mapping.vigente_desde || null, vigente_hasta: mapping.vigente_hasta || null }; return editingMap ? api.updateEgypMapeo(editingMap.id, body) : api.createEgypMapeo(body); }, onSuccess: () => { refresh(); setMapping(emptyMap); setEditingMap(undefined); } });
  const upload = useMutation({ mutationFn: () => file ? api.importEgyp(file) : Promise.reject(new Error("Selecciona un archivo Excel.")), onSuccess: () => void queryClient.invalidateQueries({ queryKey: ["egyp-summary"] }) });
  return <Stack spacing="6">
    <PageTitle title="Configuración EGyP" description="Administra líneas de negocio, rubros, reglas de mapeo e importaciones con trazabilidad." />
    <Card><CardBody><Stack spacing="4"><Text fontWeight="semibold">Importar asientos</Text><Text fontSize="sm" color="gray.500">La plantilla usa la hoja Asientos. Un rubro o centro informado en la fila tiene prioridad sobre el mapeo de cuenta.</Text><HStack flexWrap="wrap"><Input type="file" accept=".xlsx" p="1" maxW="360px" onChange={(event) => setFile(event.target.files?.[0])} /><Button variant="outline" onClick={() => void api.download("/api/v1/ganancias-perdidas/plantilla.xlsx").then((blob) => download(blob, "plantilla_egyp.xlsx"))}>Descargar plantilla</Button><Button colorScheme="brand" isDisabled={!file} isLoading={upload.isPending} onClick={() => upload.mutate()}>Importar</Button></HStack>{upload.isError && <ErrorBox error={upload.error} />}{upload.data && <Text color="green.600">Se importaron {upload.data.filas_nuevas} asientos en el lote {upload.data.lote_id}.</Text>}</Stack></CardBody></Card>
    <Editor title={editingCenter ? "Editar línea de negocio" : "Nueva línea de negocio"} onSubmit={() => saveCenter.mutate()} loading={saveCenter.isPending} error={saveCenter.error}><SimpleGrid columns={{ base: 1, md: 3 }} spacing="3"><Field label="Código" required><Input value={center.codigo} onChange={(event) => setCenter({ ...center, codigo: event.target.value })} /></Field><Field label="Nombre" required><Input value={center.nombre} onChange={(event) => setCenter({ ...center, nombre: event.target.value })} /></Field><Field label="Orden"><Input type="number" value={center.orden} onChange={(event) => setCenter({ ...center, orden: event.target.value })} /></Field></SimpleGrid></Editor>
    {centers.data && <DataTable headers={["Código", "Línea de negocio", "Estado", ""]} empty="No hay líneas de negocio.">{centers.data.map((item) => <Tr key={item.id}><Td>{item.codigo}</Td><Td>{item.nombre}</Td><Td><Status active={item.is_active} /></Td><Td><HStack><Button size="sm" onClick={() => { setEditingCenter(item); setCenter({ codigo: item.codigo, nombre: item.nombre, orden: String(item.orden) }); }}>Editar</Button>{item.is_active && <Button size="sm" variant="ghost" colorScheme="red" onClick={() => confirmDelete(item.nombre) && api.deleteEgypCentro(item.id).then(refresh)}>Inactivar</Button>}</HStack></Td></Tr>)}</DataTable>}
    <Editor title={editingRubro ? "Editar rubro" : "Nuevo rubro"} onSubmit={() => saveRubro.mutate()} loading={saveRubro.isPending} error={saveRubro.error}><SimpleGrid columns={{ base: 1, md: 5 }} spacing="3"><Field label="Código" required><Input value={rubro.codigo} onChange={(event) => setRubro({ ...rubro, codigo: event.target.value })} /></Field><Field label="Nombre" required><Input value={rubro.nombre} onChange={(event) => setRubro({ ...rubro, nombre: event.target.value })} /></Field><Field label="Naturaleza" required><Select value={rubro.naturaleza} onChange={(event) => setRubro({ ...rubro, naturaleza: event.target.value as Naturaleza })}>{["INGRESO", "CONTRA_INGRESO", "COSTO_VENTA", "GASTO_OPERATIVO", "INGRESO_FINANCIERO", "GASTO_FINANCIERO", "IMPUESTO"].map((value) => <option key={value}>{value}</option>)}</Select></Field><Field label="Rubro padre"><Select value={rubro.padre_id} onChange={(event) => setRubro({ ...rubro, padre_id: event.target.value })}><option value="">Sin padre</option>{rubros.data?.filter((item) => item.is_active && item.id !== editingRubro?.id).map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</Select></Field><Field label="Orden"><Input type="number" value={rubro.orden} onChange={(event) => setRubro({ ...rubro, orden: event.target.value })} /></Field></SimpleGrid></Editor>
    {rubros.data && <DataTable headers={["Código", "Rubro", "Naturaleza", "Estado", ""]} empty="No hay rubros.">{rubros.data.map((item) => <Tr key={item.id}><Td>{item.codigo}</Td><Td>{item.nombre}</Td><Td>{item.naturaleza}</Td><Td><Status active={item.is_active} /></Td><Td><HStack><Button size="sm" onClick={() => { setEditingRubro(item); setRubro({ codigo: item.codigo, nombre: item.nombre, naturaleza: item.naturaleza, padre_id: item.padre_id ?? "", orden: String(item.orden) }); }}>Editar</Button>{item.is_active && <Button size="sm" variant="ghost" colorScheme="red" onClick={() => confirmDelete(item.nombre) && api.deleteEgypRubro(item.id).then(refresh)}>Inactivar</Button>}</HStack></Td></Tr>)}</DataTable>}
    <Editor title={editingMap ? "Editar mapeo" : "Nuevo mapeo de cuenta"} onSubmit={() => saveMap.mutate()} loading={saveMap.isPending} error={saveMap.error}><SimpleGrid columns={{ base: 1, md: 5 }} spacing="3"><Field label="Cuenta contable" required><Input value={mapping.cuenta_contable} onChange={(event) => setMapping({ ...mapping, cuenta_contable: event.target.value })} /></Field><Field label="Rubro" required><Select value={mapping.rubro_id} onChange={(event) => setMapping({ ...mapping, rubro_id: event.target.value })}><option value="">Selecciona rubro</option>{rubros.data?.filter((item) => item.is_active).map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</Select></Field><Field label="Centro predeterminado"><Select value={mapping.centro_resultado_id} onChange={(event) => setMapping({ ...mapping, centro_resultado_id: event.target.value })}><option value="">Sin asignar</option>{centers.data?.filter((item) => item.is_active).map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</Select></Field><Field label="Vigente desde"><Input type="date" value={mapping.vigente_desde} onChange={(event) => setMapping({ ...mapping, vigente_desde: event.target.value })} /></Field><Field label="Vigente hasta"><Input type="date" value={mapping.vigente_hasta} onChange={(event) => setMapping({ ...mapping, vigente_hasta: event.target.value })} /></Field></SimpleGrid></Editor>
    {mappings.data && <DataTable headers={["Cuenta", "Rubro", "Centro", "Vigencia", "Estado", ""]} empty="No hay mapeos.">{mappings.data.map((item) => <Tr key={item.id}><Td>{item.cuenta_contable}</Td><Td>{rubros.data?.find((rubroItem) => rubroItem.id === item.rubro_id)?.nombre ?? item.rubro_id}</Td><Td>{centers.data?.find((centerItem) => centerItem.id === item.centro_resultado_id)?.nombre ?? "-"}</Td><Td>{item.vigente_desde ?? "-"} a {item.vigente_hasta ?? "-"}</Td><Td><Status active={item.is_active} /></Td><Td><HStack><Button size="sm" onClick={() => { setEditingMap(item); setMapping({ cuenta_contable: item.cuenta_contable, rubro_id: item.rubro_id, centro_resultado_id: item.centro_resultado_id ?? "", vigente_desde: item.vigente_desde ?? "", vigente_hasta: item.vigente_hasta ?? "" }); }}>Editar</Button>{item.is_active && <Button size="sm" variant="ghost" colorScheme="red" onClick={() => confirmDelete(item.cuenta_contable) && api.deleteEgypMapeo(item.id).then(refresh)}>Inactivar</Button>}</HStack></Td></Tr>)}</DataTable>}
  </Stack>;
}
